#Definir un nom
name: Laravel CI
#Definir les triggers
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #Recuperer le code source
      - name: Recuperer le code source
        uses: actions/checkout@v5

      #Executer les tests
      - name: Run test
        run: cd app && composer install && php artisan key:generate && php artisan test